name: Reusable Dependency Scan Job

on:
  workflow_call:

jobs:
  dependency-scan:
    name: Dependency Scanning (OWASP Dependency-Check)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check.zip -d ./dependency-check

      - name: Run Dependency-Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --project "JavaProject" \
            --scan . \
            --format "XML" \
            --out dependency-check-report \
            --disableAssembly

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
