name: Secret Scan with Gitleaks CLI

on:
  workflow_call:

jobs:
  secret-scan:
    name: Secret Scanning (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to allow history scanning if needed

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/

      - name: Run Gitleaks with custom rules
        run: |
          gitleaks detect \
            --source=. \
            --config-path=.gitleaks.toml \
            --verbose \
            --exit-code=1
