name: Reusable Secret Scan Job

on:
  workflow_call:

jobs:
  secret-scan:
    name: Secret Scanning (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks with custom rules
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --config-path=.gitleaks.toml --verbose
