name: Main Security Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 3 * * 1"

jobs:
  sast:
    uses: ./.github/workflows/sast-template.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan-template.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan-template.yml

  linting:
    uses: ./.github/workflows/linting-template.yml
